services:
  db:
    image: postgres:18
    container_name: careerpilot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: careerpilot
      POSTGRES_USER: careerpilot
      POSTGRES_PASSWORD: careerpilot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: